### ISSUE TITLE
Secondary account creations are displayed as if the creator's account is being created

### ISSUE THREAD

**Issue by MarcoAurelioWM** [countervandalism/CVNBot#37] opened 2018-01-05 22:35 UTC
`User:A` is registered already and creates an account for `User:B`. CVNBot will however display that User:A has been created.

 - Recent example: `<CVNBot5> New user [[m:User:JGulingan (WMF)]] created. Block: https://meta.wikimedia.org/wiki/Special:Blockip/JGulingan_%28WMF%29`

 - Real log: `(User creation log); 22:26 . . User account EYildrim (WMF) (talk | contribs | block) was created by JGulingan (WMF) (talk | contribs | block) and password was sent by email ‎(WMF Fellow)`

 - Suggested output: `New user $new_user was created by $creator. Block: $blocklink`

Thank you.

**Comment by MarcoAurelioWM** [comment] 2018-01-05 22:50
Apparently [this is already supported](https://github.com/countervandalism/CVNBot/blob/b6ca1d6911e987c5e12ba3bfd6887665b5ca76c1/src/Console.msgs#L100) but maybe it is not recognizing the current log entries? File was last updated 5 years ago.

**Comment by Krinkle** [comment] 2018-12-27 02:45
Duplicate of #19.

**Closed by Krinkle** 2018-12-27 02:45 UTC
Labels: type-problem
